// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoAZRNuyno5jUCvOaHPoCqwKQB44RVuXM',
    appId: '1:563703510074:web:ef94e97912d908bb2ef103',
    messagingSenderId: '563703510074',
    projectId: 'chat-4e442',
    authDomain: 'chat-4e442.firebaseapp.com',
    databaseURL: 'https://chat-4e442-default-rtdb.firebaseio.com',
    storageBucket: 'chat-4e442.appspot.com',
    measurementId: 'G-71Y65WPK04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBymd-ysZUZOMcR_terdXyU3lLOC7RoPL0',
    appId: '1:563703510074:android:81c55debb4f92a862ef103',
    messagingSenderId: '563703510074',
    projectId: 'chat-4e442',
    databaseURL: 'https://chat-4e442-default-rtdb.firebaseio.com',
    storageBucket: 'chat-4e442.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-WpQcFn7CsqHar6WZt7Ie_xcwjHokvwY',
    appId: '1:563703510074:ios:ec43db413930356e2ef103',
    messagingSenderId: '563703510074',
    projectId: 'chat-4e442',
    databaseURL: 'https://chat-4e442-default-rtdb.firebaseio.com',
    storageBucket: 'chat-4e442.appspot.com',
    androidClientId: '563703510074-6av8vutca4ospk9lthvrd0366182jj4k.apps.googleusercontent.com',
    iosClientId: '563703510074-tnf4gllj22hpocooctic9linc01r4g4v.apps.googleusercontent.com',
    iosBundleId: 'com.pranjal.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-WpQcFn7CsqHar6WZt7Ie_xcwjHokvwY',
    appId: '1:563703510074:ios:ec43db413930356e2ef103',
    messagingSenderId: '563703510074',
    projectId: 'chat-4e442',
    databaseURL: 'https://chat-4e442-default-rtdb.firebaseio.com',
    storageBucket: 'chat-4e442.appspot.com',
    androidClientId: '563703510074-6av8vutca4ospk9lthvrd0366182jj4k.apps.googleusercontent.com',
    iosClientId: '563703510074-tnf4gllj22hpocooctic9linc01r4g4v.apps.googleusercontent.com',
    iosBundleId: 'com.pranjal.chat',
  );
}
